(in-package :cl-user)
(defpackage :cl3a
  (:use :cl)
  (:import-from :cl3a.dotprod
                :dv*v :lv*v)
  (:import-from :cl3a.norm
                :dnorm :lnorm)
  (:import-from :cl3a.add-vector
                :dv+v :lv+v)
  (:import-from :cl3a.rotate
                :drotate :lrotate)
  (:import-from :cl3a.mvmult
                :dm*v :lm*v)
  (:import-from :cl3a.mmmult
                :dm*m :lm*m)
  (:export :dv*v :lv*v
           :dnorm :lnorm
           :dv+v :lv+v
           :drotate :lrotate
           :dm*v :lm*v
           :dm*m :lm*m))
(in-package :cl3a)
